# Generated by Django 2.1 on 2019-03-23 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='simulation_flag',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
