# Generated by Django 2.0.5 on 2019-03-11 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(blank=True, max_length=50)),
                ('initial_num', models.IntegerField(blank=True)),
                ('num_used', models.IntegerField(blank=True)),
                ('num_available', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
