# Generated by Django 2.0.5 on 2019-03-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('beds', '0002_auto_20190303_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BedAvailability',
            new_name='Beds',
        ),
    ]
