# Generated by Django 2.0.5 on 2019-03-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('beds', '0003_auto_20190306_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beds',
            new_name='Bed',
        ),
    ]
