# Generated by Django 2.0.5 on 2019-03-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_auto_20190306_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='org_id',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='bed',
            name='initial_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='num_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='num_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
